### ISSUE TITLE
Doesn't have support for angular 2-universal

### ISSUE THREAD

**Issue by areednehvi** [DethAriel/ng-recaptcha#75]
EXCEPTION: Uncaught (in promise): ReferenceError: window is not defined
ReferenceError: window is not defined
    at RecaptchaLoaderService.init (I:\BQE Website\BQEWebsite\dist-temp\index.js:28989:9)
    at new RecaptchaLoaderService (I:\BQE Website\BQEWebsite\dist-temp\index.js:28981:14)
    at NgModuleInjector.get (/MainModule/module.ngfactory.js:1438:89)
    at NgModuleInjector.MainModuleInjector.getInternal (/MainModule/module.ngfactory.js:1586:63)
    at NgModuleInjector.get (I:\BQE Website\BQEWebsite\dist-temp\index.js:37910:27)
    at ElementInjector.get (I:\BQE Website\BQEWebsite\dist-temp\index.js:59583:48)
    at ReflectiveInjector_._getByKeyDefault (I:\BQE Website\BQEWebsite\dist-temp\index.js:59417:24)
    at ReflectiveInjector_._getByKey (I:\BQE Website\BQEWebsite\dist-temp\index.js:59383:25)
    at ReflectiveInjector_.get (I:\BQE Website\BQEWebsite\dist-temp\index.js:59192:21)
    at ElementInjector.get (I:\BQE Website\BQEWebsite\dist-temp\index.js:59583:48)
ORIGINAL STACKTRACE:
Error: Uncaught (in promise): ReferenceError: window is not defined

**Comment by DethAriel** [comment]
Hello, @areednehvi ! Could you please follow the new issue template and add more information? This should have been fixed by [v3.0.0](https://github.com/DethAriel/ng-recaptcha/blob/master/CHANGELOG.md#300-2017-08-30)

**Comment by areednehvi** [comment]
@DethAriel  i added it Recaptcha by directly by following recaptcha documentation. it worked for me by creating a directive and rest was my server side code. Anyways , i will try v3.0 as well. Thank You

**Comment by DethAriel** [comment]
@areednehvi did the new version solve your issue?

**Comment by MortezaAghili** [comment]
@DethAriel I have this error on version **`3.0.5`**


```
dist/ngfactory/node_modules/ng-recaptcha/recaptcha/recaptcha.component.ngfactory.ts:9
import * as i0 from '@angular/core';
^^^^^^
SyntaxError: Unexpected token import


```

**Comment by sjsnider** [comment]
I have only been using it client side and everything has been working great.  Trying to make a universal app now.  I have no issues building and serving server side, but clicking doesn't seem to execute captchaRef.execute() anymore (I am for certain waiting until the client side app has loaded).  I dont get any errors as a hint either unfortunately.  Here's the recaptcha component and the button in my form.  Any thoughts?

```
<re-captcha class="g-recaptcha" #captchaRef="reCaptcha" formControlName="recaptcha" (resolved)="$event && _login()"></re-captcha>

    <div class="cu-form__row cu-form__row_last">
      <button class="cu-btn cu-btn_block cu-btn_spinner" type="submit" [disabled]="loading"  (click)="captchaRef.execute()">
        <div class="cu-btn__text">Log In</div>
      </button>
```

**Comment by sjsnider** [comment]
whoops, disregard, had changed something in my AppModule and I don't think the sitekey was getting set.  Testing now, but pretty sure I'm all good.
